### ISSUE TITLE
Script for Tenda that offers tea is wrong.

### ISSUE THREAD

**Issue by dingledoop** [mrtenda/CoilSnake#108]
After decompiling the script and then compiling again without making any changes, the Tenda that offers you tea has incorrect dialogue, some of which seems to be from Tracy. As well as the 'yes' and 'no' options, he also has 'check out' and 'store' options. Selecting 'Yes' acts like you asked Tracy to Store, selecting 'No' acts like you asked her to Check out, and selecting 'Check out' or 'Store' acts like you exited dialogue when talking to Tracy. 

![tenda](https://cloud.githubusercontent.com/assets/13398624/8763939/f15383a4-2d83-11e5-8c64-d54e07a98db3.png)

**Comment by kiij** [comment]
Thanks for the heads up! CoilSnake actually relies on [CCScriptWriter](https://github.com/Lyrositor/CCScriptWriter) for its "Decompile Script" functionality, so I think this issue should be opened on that project.

**Comment by ShadowOne333** [comment]
This issue is quite old, but I think the most recent versions of CCScriptWriter do decompile this part of the script properly now.
Can this issue be closed?

**Comment by mrtenda** [comment]
@ShadowOne333 just tested this and it works in the latest CoilSnake now
