### ISSUE TITLE
Translation Features

### ISSUE THREAD

**Issue by mrtenda** [mrtenda/CoilSnake#109]
Features necessary to help translations
- [x] Sound Stone graphic
- [ ] Cast names
- [ ] "The End...?" graphic
- [ ] Staff Credits text
- [ ] BOOM image

**Comment by ShadowOne333** [comment]
Most of these have been covered in the Tutorial section of CoilSnake.

"The End" graphic:
https://github.com/mrtenda/CoilSnake/wiki/Tutorial%3A-Translating-%22THE-END...-%3F%22-text

Staff Credits text:
https://github.com/mrtenda/CoilSnake/wiki/Tutorial%3A-Staff-credits-text

Cast Credits text:
https://github.com/mrtenda/CoilSnake/wiki/Tutorial:-Cast-Sequence-credits-text

The BOOM image is the only one I haven't translated yet, but should be as easy as simply knowing what is the range for that text and decompressing it for editing following the [Export and Modify Compressed Graphics](https://github.com/mrtenda/CoilSnake/wiki/Tutorial%3A-Export-and-Modify-Compressed-Graphics) section of the Tutorial as well.
