### ISSUE TITLE
It's not letting me decompile text!

### ISSUE THREAD

**Issue by craftersshaft** [mrtenda/CoilSnake#111]
When I try to decompile text, I get an error. I'm using Windows 10. I'm not saving it to the normal text folder, but that doesn't work either.

**Comment by TreGreeny** [comment]
coulsnake can't decompile if any direction - to the folder or file - has cyrillic symbols in it.

Каменский Илья

**Comment by john-soklaski** [comment]
Decompilation should already work with unicode paths in the latest version.

Compilation still has an issue with unicode paths, so I issued PR to ccscript that will add Unicode support on Windows: https://github.com/tripped/ccscript_legacy/pull/7

**Comment by SeniorSnore** [comment]
I am having the same error. Has anyone solved this? Here is my error message 
![image](https://user-images.githubusercontent.com/15458981/59545421-fb888e00-8eeb-11e9-8ac1-53bf704b7244.png)

**Comment by mrtenda** [comment]
Unicode paths support added with https://github.com/jamsilva/ccscript_legacy/commit/5ffb56b494923a8efeb818f432210f88f63b21e0
