### ISSUE TITLE
PSI Rockin won't change name.

### ISSUE THREAD

**Issue by MaxHero13** [mrtenda/CoilSnake#113]
I want to change PSI(????) to PK(????) in the psi_name_table.yml, with the (????) being the Favorite Thing, but when I edit it, the name in-game stays the same.
What can I do?

**Comment by ShadowOne333** [comment]
You have to include the asm65816.ccs file into your 'ccscript' folder.
Also, once you have it, create a new .ccs file and name it to whatever you want. psi-to-pk.ccs or whatever.
Inside that file, copy the following code:

`/*Change PSI Rockin to PK Rockin */
ROM[0xC1C415] = byte [0] 0x26
ROM[0xC1FE3D] = byte [0] 0x80
ROM[0xC1FE42] = byte [0] 0x7B`

That should change the "PSI" letters in the favorite thing attack to "PK".

**Comment by vince94** [comment]
You need to delete your .srm file as well if you created it before introducing this change, a save file that was created with "PSI" instead of "PK" in there will display weird iirc

**Comment by mrtenda** [comment]
See above response by vince

**Comment by MAGNAT2645** [comment]
vince94's solution doesn't work. PSI prefix stays same ('ОСЗ' in cyrillic font) so i can't override it via YML config. Is there any way to do it via CCScript? I want to change 'PSI ????' to 'ПСИ ????' (cyrillic font).

**Comment by MAGNAT2645** [comment]
I found that
> ASM routine at **0x01C60F** acts as a functional override, which uses the "PSI Favorite thing" string stored in the game's save memory.

But CoilSnake prints "bad virtual address" error.

**Comment by mrtenda** [comment]
Did you try ShadowOne333's solution? You need to do both his solution and vince's solution

**Comment by MAGNAT2645** [comment]
But how exactly i can change PSI prefix with these 3 pointers?

**Comment by ShadowOne333** [comment]
Can you please post your psi_name_table YML files? Also Id would help if you could post the Font file for the Cyrillic alphabet you added for reference.

I need to make sure what is it that tou have in both to debug the issue.

**Comment by MAGNAT2645** [comment]
psi_name_table:
```
0:
  Name: '[81][83][7A] (????) '
1:
  Name: '[81][83][7A] [80][94][A0][9F][C3] '
2:
  Name: '[81][83][7A] [7E][A0][A2][A0][99] '
3:
  Name: '[81][83][7A] [74][A2][A0][99][91] '
4:
  Name: '[81][83][7A] [73][A3][A1][C2][AA][9C][91] '
5:
  Name: '[81][83][7A] [79][93][96][99][95][A0][A1][91][95] '
6:
  Name: '[78][9A][99][9F][C3]++ '
7:
  Name: '[7D][96][A9][96][9F][9A][96] '
8:
  Name: '[B0][9A][A4] '
9:
  Name: '[81][83][7A] [B0][9A][A4] '
10:
  Name: '[71][A4][91][9C][91]++ '
11:
  Name: '[79][91][C0][9A][A4][91]-- '
12:
  Name: '[74][9A][A1][9F][A0][99] '
13:
  Name: '[81][83][7A] [7E][91][94][9F][9A][A4] '
14:
  Name: '[81][91][A2][91][9D][9A][A9] '
15:
  Name: '[7E][A0][99][94][A0][9D][A0][9E] '
16:
  Name: '[84][96][9D][96][A1][A0][A2][A4] '
```
Font image:
![](https://i.imgur.com/Vn0mo0j.png)

Font width:
```
0: 2
1: 2
2: 3
3: 2
4: 5
5: 9
6: 7
7: 2
8: 3
9: 3
10: 3
11: 5
12: 2
13: 2
14: 2
15: 4
16: 5
17: 5
18: 5
19: 5
20: 5
21: 5
22: 5
23: 5
24: 5
25: 5
26: 2
27: 3
28: 3
29: 5
30: 3
31: 4
32: 5
33: 6 #А
34: 5 #Б
35: 5 #В
36: 3 #Г
37: 5 #Д
38: 4 #Е
39: 4 #Ё
40: 5 #Ж
41: 4 #З
42: 5 #И
43: 5 #Й
44: 4 #К
45: 4 #Л
46: 5 #М
47: 5 #Н
48: 5 #О
49: 5 #П
50: 5 #Р
51: 5 #С
52: 4 #Т
53: 5 #У
54: 7 #Ф
55: 5 #Х
56: 6 #Ц
57: 5 #Ч
58: 7 #Ш
59: 5
60: 4
61: 6
62: 4
63: 5
64: 1 #[90] - 1px space
65: 4 #а
66: 4 #б
67: 4 #в
68: 3 #г
69: 4 #д
70: 4 #е
71: 4 #ё
72: 5 #ж
73: 4 #з
74: 4 #и
75: 4 #й
76: 4 #к
77: 3 #л
78: 5 #м
79: 4 #н
80: 4 #о
81: 4 #п
82: 4 #р
83: 4 #с
84: 3 #т
85: 4 #у
86: 5 #ф
87: 4 #х
88: 5 #ц
89: 4 #ч
90: 7 #ш
91: 2
92: 5
93: 2
94: 6
95: 7
96: 8 #Щ
97: 6 #Ъ
98: 6 #Ы
99: 4 #Ь
100: 4 #Э
101: 6 #Ю
102: 5 #Я
103: 255
104: 255
105: 255
106: 255
107: 255
108: 255
109: 255
110: 255
111: 255
112: 8 #щ
113: 5 #ъ
114: 5 #ы
115: 4 #ь
116: 4 #э
117: 5 #ю
118: 4 #я
119: 255
120: 255
121: 255
122: 255
123: 255
124: 255
125: 255
126: 255
127: 255
```

**Comment by ShadowOne333** [comment]
Oh boy.
I am not sure if modifying the entire Font characters would be such a good idea...

But anyway, let's start with this.

First off, I believe the very first PSI doesn't need an apostrophe, neither at the end nor the beginning.
So try doing something like this instead:

> 0:
>   Name: [81][83][7A] (????) # <<< This doesn't change original PSI prefix

If that doesn't work, let us know so we can proceed with the other suggestions I have to hopefully fix this.

**Comment by MAGNAT2645** [comment]
```
0:
  Name: [81][83][7A] (????) 
```
```
ParserError: while parsing a block mapping
  in "C:/Games/EB RUS\psi_name_table.yml", line 2, column 3
did not find expected key
  in "C:/Games/EB RUS\psi_name_table.yml", line 2, column 13
```

**Comment by ShadowOne333** [comment]
Okay try the following two things now:

```
0:
  Name: QSJ(????) 
```

```
0:
  Name: 'QSJ(????)' 
```

And also try:

```
0:
  Name: '[A0][B0][A1] (????)'
```

I know the last one is not the corresponding characters, but I just want to know what the game does with those values compiled.

**Comment by MAGNAT2645** [comment]
Tried 3rd method

![](https://i.imgur.com/mJtvFF2.png)

Same...

(trying 1st and 2snd)

**Comment by MAGNAT2645** [comment]
1st and 2snd doesn't change prefix too (tried with game reset and without SMC file)

**Comment by ShadowOne333** [comment]
Okay now try this.
Put this in a ccs file:
```
ROM[0xC1C415] = byte [0] 0x81
ROM[0xC1FE3D] = byte [0] 0x83
ROM[0xC1FE42] = byte [0] 0x7A
```

**Comment by MAGNAT2645** [comment]
![](https://i.imgur.com/6CdYATD.png)

**Comment by ShadowOne333** [comment]
That's really weird.
It shouldn't delete the name there, at all.

Verify that you don't have any other code that could be affecting those ROM addresses I gave you.
I suggest that you try this in a clean CoilSnake decompilation, only copy the new font image and its corresponding yml file, and then add the code I gave you to a new ccs file.

Also, write
`import asm65816`
At the top of the ccs file (very beginning) that you write this code in.

**Comment by MAGNAT2645** [comment]
Tried with Vanilla Expanded version.
![](https://i.imgur.com/TECEuil.png)

**Comment by ShadowOne333** [comment]
Ah wait, it was a mistake on my part.
The first ROM address was wrong.
Replace the ROM commands I gave you earlier with these ones:
```
ROM[0xC1FE38] = byte [0] 0x81
ROM[0xC1FE3D] = byte [0] 0x83
ROM[0xC1FE42] = byte [0] 0x7A
```

**Comment by MAGNAT2645** [comment]
Oh, thanks. Now it's working!
![](https://i.imgur.com/cWem3jA.png)

**Comment by ShadowOne333** [comment]
Awesome!
Glad it's finally working :)
We can now properly close down this issue.

**Comment by mrtenda** [comment]
Should any of this information be added to the wiki for future users? (Or even just adding a link on the wiki to this issue)

**Comment by MAGNAT2645** [comment]
Maybe YML PSI(????) don't work only for Non-English fonts. So i think these 3 pointers above should be added as additional note for those who want to make localization for their language.

**Comment by ShadowOne333** [comment]
The last problem you mention with transparency is something that can be fixed with the tile editor itself.
I would recommend that you take the STOP sign as reference to fix the transparency issue, since I don't recall exactly how I fixed some of the tiles for the Spanish translation, but checking the STOP sign tiles should give you a good base to know how to do so.

The STOP sign has transparency enabled for the corners of the sign, but not the sign itself.
I think all you might need to do is simply repaint the pixels that have transparency, either with the same color in BOTH squares of the tile editor (the one above and the one below), or with another similar colour.
It's one of the two, but I can't recall which one.

**Comment by MAGNAT2645** [comment]
I know that i should reply here but i cant understand this thing:
![изображение](https://user-images.githubusercontent.com/11666918/54201413-69897780-44ef-11e9-8a6e-d2089b309e58.png)

There's nothing about this red X on Tile Editor wiki page.

**Comment by mrtenda** [comment]
Yes, that's correct.

**Comment by MAGNAT2645** [comment]
If i can't draw on foreground then how i can fix that transparent tile issue?

**Comment by mrtenda** [comment]
Some tiles do not support drawing on the foreground. (This is just how EarthBound works, I can't do anything about that...) If you want to draw on the foreground, you can use a different tile instead.
