### ISSUE TITLE
Hello!

### ISSUE THREAD

**Issue by lysander2033** [mrtenda/CoilSnake#115]
Hi.
I am starting  to hack earthbound and I am using the coilsnake tutorial to do so. I am at "Your first hack" part. I have been doing everything fine until the compile part.
When I press 'compile' this messahe appears:
'ERROR: 'Project' object has no attrbute 'version'
I don't know what I did wrong.
Could you help me?
Thank you.

**Comment by LittleCube13** [comment]
Look through the folder you Decompiled to and try to find your Project.snake file. If you have it, it's something else, if not, there might be something wrong with your ROM.

**Comment by ShadowOne333** [comment]
If you still can't find your "Project.snake" file, try decompiling a fresh project and use that one as the base.
If not, then try using the "Upgrade" tab from CoilSnake, that should create a proper Project.snake file.
