### ISSUE TITLE
Issue with compiling

### ISSUE THREAD

**Issue by xXFlightPVPXx** [mrtenda/CoilSnake#116]
All was going well till this happened:

Starting compilation...
Compiling Project...
Compiling Used Ranges...
Finished compiling Used Ranges in 0.00s
Compiling Patches...
Finished compiling Patches in 0.01s
Compiling Character Substitutions...
Finished compiling Character Substitutions in 0.00s
Compiling CCScript Labels...
Finished compiling CCScript Labels in 0.00s
Compiling Skip Names...
Finished compiling Skip Names in 0.00s
Compiling Miscellaneous Text...
Finished compiling Miscellaneous Text in 0.02s
Compiling NPC Placements...
Finished compiling NPC Placements in 0.73s
Compiling Doors...
Finished compiling Doors in 1.38s
Compiling Sprite Groups...
Finished compiling Sprite Groups in 9.34s
Compiling Miscellaneous Tables...
ERROR: TableError: Error while parsing in "Text Pointer 1" in entry #1 in table "NPC_CONFIG_TABLE":
TableSchemaError: Error while parsing "Text Pointer 1":
TableEntryInvalidYmlRepresentationError: Unknown pointer label[data_28.l_0xc74c07]

Can someone please explain what's happening?

**Comment by LittleCube13** [comment]
It looks like that label doesn't exist. This isn't really something that can be fixed easily unless you know what the label is supposed to be. I'll take a look in a bit and tell you what to do.

**Comment by xXFlightPVPXx** [comment]
@LittleCube13 Don't worry, That was due to a typo, Now CoilSnake won't even start,
