### ISSUE TITLE
Gas Station logo.

### ISSUE THREAD

**Issue by xXFlightPVPXx** [mrtenda/CoilSnake#118]
Basically, This is what I get if I try to change the Gas Station logo:
- Reading TownMaps/Onett
- Reading TownMaps/Twoson
- Reading TownMaps/Threed
- Reading TownMaps/Fourside
- Reading TownMaps/Scaraba
- Reading TownMaps/Summers
- Reading town map icons
- Reading Logos/Nintendo
- Reading Logos/APE
- Reading Logos/HALKEN
- Reading Logos/ProducedBy
- Reading Logos/PresentedBy
- Reading gas station logo
ERROR: 'NoneType' object has no attribute '__getitem__' <----

Can you actually change the Gas Station logo?

**Comment by LittleCube13** [comment]
Yes. It is located in the Logos folder. What is the filename of the ROM you are trying to decompile?

**Comment by xXFlightPVPXx** [comment]
Oh, no. I'm trying to compile the ROM. Sorry about that...

**Comment by LittleCube13** [comment]
oh ha, I didn't know it, but I missed a lot of your question. May I ask which operating system you're using?

In addition to that, are there 3 images appertaining to the GasStation? If so, are they named GasStation1, 2, 3?

**Comment by xXFlightPVPXx** [comment]
OK,
I'm using Windows 10, and all logos gas station logos are named correctly.

**Comment by xXFlightPVPXx** [comment]
Hm, I check all the names again, one was called 'GsStation1', Renamed it to it's original name, but it still isn't working. Same error.

**Comment by LittleCube13** [comment]
would you be okay with sending me your project? Perhaps I can help you better.

**Comment by xXFlightPVPXx** [comment]
Perhaps, as a last resort, is there anything else I can try first?

**Comment by xXFlightPVPXx** [comment]
OK, I've compiled it, I will close the issue if it works in the ROM.

**Comment by xXFlightPVPXx** [comment]
Yes, I've got it to work in the ROM, But it flashes pink instead of the normal colors. I don't really see it as that big a deal though. So I guess I'll just close this now.
