### ISSUE TITLE
TableEntryInvalidYmlRepresentationError: Unknown pointer label[robot.hello_world]

### ISSUE THREAD

**Issue by techytom11** [mrtenda/CoilSnake#119]

**Comment by LittleCube13** [comment]
Which yml file are you editing?

**Comment by techytom11** [comment]
npc_config_table.yml

**Comment by LittleCube13** [comment]
Is there a ccs file in your project's ccscript folder called robot, and does it contain a label called hello_world?

**Comment by LittleCube13** [comment]
Also, the file must be named robot.ccs

**Comment by techytom11** [comment]
yes

**Comment by LittleCube13** [comment]
Try removing the underscore in the label name.

**Comment by techytom11** [comment]
it does it anyway, underscore or not

**Comment by LittleCube13** [comment]
Huh. Would you mind sending me your project? I'll see if I can't find the issue.

**Comment by techytom11** [comment]
Sure just a moment, generating gdrive link

**Comment by techytom11** [comment]
Never mind, I fixed it. I accidentally named the file robot.css instead of robot.ccs. Thanks anyway!
