### ISSUE TITLE
Image using the correct palette is invalid?

### ISSUE THREAD

**Issue by xXFlightPVPXx** [mrtenda/CoilSnake#120]
Hello!

I've run into a problem with CoilSnake.

Whenever I change a sprite and use an indexed palette, it won't compile.

I get the '001.png uses an invalid palette' error.

UPD: Only, Palette 0 works, I tried all the palettes out, and it showed that only one worked.

**Comment by xXFlightPVPXx** [comment]
Also, Whenever I compile, when compilation is finished, '002.png' deletes itself.

**Comment by LittleCube13** [comment]
Wowzers. That's not good.

Well, firstly, what image editor are you using? I'd recommend GraphicsGale, and I would NOT recommend GIMP. That one gets into arguments with CoilSnake. Photoshop also works really well with it.

**Comment by xXFlightPVPXx** [comment]
I'm using Adobe Photoshop,

**Comment by LittleCube13** [comment]
Huh, that's weird.

What are you editing? Battle Sprites, NPCs...etc.

**Comment by xXFlightPVPXx** [comment]
I'm editing pretty much all of them, mainly NPCs.

**Comment by LittleCube13** [comment]
Try GraphicsGale. Maybe that'll work better.

**Comment by xXFlightPVPXx** [comment]
Alright, I'll try that in a bit.

**Comment by xXFlightPVPXx** [comment]
Ah, problem fixed on Photoshop, turns out I accidentally messed up the palette whenever I opened it.
