### ISSUE TITLE
BattleBGs aren't compiling.

### ISSUE THREAD

**Issue by xXFlightPVPXx** [mrtenda/CoilSnake#122]
Heya,

I'm now having troubles compiling BattleBGs after changing the distortion data for them,

Compiling Battle Backgrounds...
ERROR: Don't know how to read graphical tile data of bpp[5]

It worked the first few times I changed them, then it just started doing this.

**Comment by LittleCube13** [comment]
Haha, did you check your last issue? I posted a recommendation there.

You see, this section of CoilSnake is for bugs/glitches that CoilSnake may have. So check the last issue you closed real quick. ;)

**Comment by xXFlightPVPXx** [comment]
Eh, Sorry. Didn't get notified when you responded.

**Comment by LittleCube13** [comment]
No worries :D
