### ISSUE TITLE
Willing to upgrade to Python 3?

### ISSUE THREAD

**Issue by john-soklaski** [mrtenda/CoilSnake#133]
I did a preliminary upgrade to Python 3.6 through a combination of 2to3 and manual fixes. You can see the changes here: https://github.com/mrtenda/CoilSnake/compare/master...john-soklaski:python3_conversion

I haven't tested it extensively yet, but de-compilation, and the gui are working.

Is this something you'd be willing to accept?

**Comment by mrtenda** [comment]
Yes, a upgrade to Python 3.x would be welcome! I would just ask that you test it all thoroughly to make sure everything still works.

**Comment by john-soklaski** [comment]
I ended up getting the python 3 conversion working pretty well. But, to prevent regressions and ensure it's done in a high-quality manner, I've decided to incrementally introduce the support, starting with https://github.com/mrtenda/CoilSnake/pull/142

**Comment by mrtenda** [comment]
Merged in! Thank you very much

**Comment by john-soklaski** [comment]
https://github.com/mrtenda/CoilSnake/pull/146 should close out this issue. :)
I hit more roadblocks than I expected keeping Python 2 support while gradually introducing Python 3 support. I would have liked to have a few more incremental changes before the PR, but it wasn't practical.
