### ISSUE TITLE
Error when trying to roundtrip compiled Rom

### ISSUE THREAD

**Issue by john-soklaski** [mrtenda/CoilSnake#134]
I'm trying to decompile a Rom that I've previously compiled, but encounter an error in the Swirls module. Is this something that should theoretically work?

I'm attempting this to figure out some differences between the outputted Rom from my Python 3.6 upgrade and the Rom the Python 2 version outputs. I'm aiming for an identical binary output.

**Repro**
```
python script/cli.py decompile C:\orig.smc C:\orig
python script/cli.py compile C:\orig C:\orig.smc C:\mod.smc
python script/cli.py decompile C:\mod.smc C:\mod
```

**Output:**
```
Decompiling Swirls...
Traceback (most recent call last):
  File "script/cli.py", line 9, in <module>
    sys.exit(main())
  File "c:\coilsnakepy2\coilsnake\ui\cli.py", line 73, in main
    args.func(args)
  File "c:\coilsnakepy2\coilsnake\ui\cli.py", line 84, in _decompile
    project_path=args.project_directory)
  File "c:\coilsnakepy2\coilsnake\ui\common.py", line 181, in decompile_rom
    module.read_from_rom(rom)
  File "c:\coilsnakepy2\coilsnake\modules\eb\SwirlModule.py", line 63, in read_from_rom
    self.swirls[i].frames_from_block(rom, animation_pointers)
  File "c:\coilsnakepy2\coilsnake\model\eb\swirls.py", line 248, in frames_from_block
    frame.from_block(block, frame_offset)
  File "c:\coilsnakepy2\coilsnake\model\eb\swirls.py", line 115, in from_block
    self.rows[i].from_block(block, offset, is_mode_01)
IndexError: list index out of range
```

**Comment by mrtenda** [comment]
Yeah, I've been aware of this, but decompiling a compiled ROM has always been outside the scope of CoilSnake for me, so I've never bothered to look into it. However, it is something that people bring up a lot. It's usually this Swirls error that causes the problem.

**Comment by john-soklaski** [comment]
The two modules that have problems are Swirl and TitleScreen.

Swirl has an issue because of the ips patch used to relocate the animation pointer table. I think this can be fixed by testing first if the ips patch has been applied and using a modified code path to load from the relocated animation pointer table.

TitleScreen has a similar problem because it relocates where the character layouts are stored, but always reads from the original location. I think I nearly have this one fixed.

**Comment by john-soklaski** [comment]
On this [line](https://github.com/mrtenda/CoilSnake/blob/master/coilsnake/modules/eb/TitleScreenModule.py#L300), what is the meaning of 0xA9?  I understand the subsequent byte is the bank address.
`rom[CHARS_LAYOUT_BANK:CHARS_LAYOUT_BANK + 2] = [0xA9, new_bank]`

The original value the 0xA9 replaces is 0xA5.

**Comment by mrtenda** [comment]
I see, your analysis makes total sense on why this is happening. Thank you for looking into this.

As for the A5/A9 thing, they're both different forms of the LDA instruction in 65816 assembly. I'm pretty sure 0xA9 loads a constant value (in this case, the `new_bank` byte), while 0xA5 loads a byte from somewhere else in memory. See: https://wiki.superfamicom.org/snes/show/65816+Reference#instructions

**Comment by john-soklaski** [comment]
Thank you! That was very helpful. I've got a fix for the TitleScreenModule now, so I've issued a pull request https://github.com/mrtenda/CoilSnake/pull/139.

**Comment by mrtenda** [comment]
Merged in 👍

**Comment by john-soklaski** [comment]
With https://github.com/mrtenda/CoilSnake/pull/141 this issue is nearly resolved.

The only remaining difference has to do with how some transparent pixels are represented in the sprite sheets after a round trip. To address this I may just move CoilSnake to use the new Hal compression library you mentioned.

**Comment by mrtenda** [comment]
Merged in #141!

Which sprite sheets are you talking about?

**Comment by john-soklaski** [comment]
Thanks! I'm referring to the images in the SpriteGroup folder. Some of the images, starting with 051.png for me, have fully transparent pixels that have different RGB values after they are re-encoded.  For instance, the top left pixel of 051.png is 144, 224, 128, 0 (RGBA), but, after roundtripping the pixel is 0, 176, 128, 0 (RGBA). Obviously in practice the pixel is fully transparent so it is irrelevant, but it does result in binary differences.

**Comment by mrtenda** [comment]
Those images are stored uncompressed in the ROM, so I doubt that changing the compression library would have any effect. There must be something else going on.

**Comment by john-soklaski** [comment]
Ah I didn't realize that. Thanks! I'll try digging into it more then.

**Comment by john-soklaski** [comment]
Looks like those SpriteGroup are getting read back with a different palette the second time. 051.png in particular is palette 6 the first time it is decompiled and palette 5 the second time.

**Comment by john-soklaski** [comment]
It's due to the way the SpriteGroups are matched with a palette during the compilation process. https://github.com/mrtenda/CoilSnake/blob/master/coilsnake/modules/eb/SpriteGroupModule.py#L86-L89

The check to see if the palettes match disregards the first RGB triplet in the palette:
`if palette.list()[3:] == self.palette_table[j][0].list()[3:]:`

When I remove the array slice, the issue is fixed:
`if palette.list() == self.palette_table[j][0].list():`

Palettes 5 and 6 end up being the same when this beginning information is disregarded (sprite_group_palettes.yml):
```
5:
  Palette:
  - (0, 176, 128)
  - (240, 240, 240)
  - (200, 200, 200)
  - (144, 160, 128)
etc.
  - (112, 112, 240)
  - (48, 32, 32)
6:
  Palette:
  - (144, 224, 128)
  - (240, 240, 240)
  - (200, 200, 200)
  - (144, 160, 128)
etc.
  - (112, 112, 240)
  - (48, 32, 32)
```

Any thoughts on why this was done this way?

**Comment by mrtenda** [comment]
I think it was done this way because GIMP doesn't properly save the first color back to the PNG. However, I don't recommend anyone use GIMP nowadays to edit these files. I think most people either edit these sprites using GraphicsGale, but I'm unsure if that program messes up the first color or not.

**Comment by john-soklaski** [comment]
Ah that makes sense! I appreciate the explanation.
Just tried editing one of the SpriteGroups in GraphicsGale and all seems to be well with the palette.

I've fixed it with https://github.com/mrtenda/CoilSnake/pull/143

**Comment by mrtenda** [comment]
Merged in, thank you!
