### ISSUE TITLE
Replace compression/decompression code with exhal library

### ISSUE THREAD

**Issue by john-soklaski** [mrtenda/CoilSnake#144]
I plan to move CoilSnake to use this library instead of the current compression implementation.
On Windows with Python 2 this is difficult because exhal uses newer C features than the compiler (Visual C++ 9.0) supports.
With the move to Python 3 I think this should be considerably easier, but I haven't attempted it yet.

**Comment by john-soklaski** [comment]
Well, I decided to give it a go with my Python 3 port. At first blush it seems to work great!

No source changes to exhal were required to get it to compile with Visual C++ 14.0 and it is almost a drop in replacement for the `_comp` and `_decomp` functions.

**Comment by mrtenda** [comment]
That's great news! Thank you for doing this.

**Comment by mrtenda** [comment]
Oh, I forgot to ask, did you notice any improvement in speed?

**Comment by john-soklaski** [comment]
I wasn't paying too much attention to the speed at the time, but as far as I remember it wasn't a huge difference.

**Comment by john-soklaski** [comment]
Resolved with https://github.com/mrtenda/CoilSnake/pull/150. See PR for performance and rom size improvements.
