### ISSUE TITLE
ERROR: unsigned byte integer is greater than maximum

### ISSUE THREAD

**Issue by Rocadinis** [mrtenda/CoilSnake#163]
Hi! I'm currently having a problem with CoilSnake. When I try to compile the project, it produces the following error:

Starting compilation...

Compiling CCScript

Finished compiling CCScript

Compiling Project C:/Users/User/Desktop/backup/Projeto

Compiling Used Ranges...

Finished compiling Used Ranges in 0.00s

Compiling Patches...

Finished compiling Patches in 0.00s

Compiling Character Substitutions...

Finished compiling Character Substitutions in 0.00s

Compiling CCScript Labels...

Finished compiling CCScript Labels in 0.03s

Compiling Skip Names...

Finished compiling Skip Names in 0.00s

Compiling Miscellaneous Text...

ERROR: unsigned byte integer is greater than maximum

My guess is that there's an error in my text_misc.yml file. Still, how can I solve this?

**Comment by ShadowOne333** [comment]
Did you modify any value in that file?
It would be better if you let us know what values you modified from there, since it seems to be a problem with one numeric value in that file.

**Comment by Rocadinis** [comment]
Well, it's nice to see that my post was answered after MONTHS... Anyway, yes, I did modify some values, such as the translations for the illnesses. Could it be because of punctuation such as tildas?

**Comment by ShadowOne333** [comment]
That could be it, yes.
If I recall correctly, YML files do not support accentuated characters, you might have to use their hex values instead (as in [B5] or whatever it is).
Try changing all characters with accents to normal alphabet character from English, and see if it compiles then.

**Comment by Rocadinis** [comment]
I changed the punctuation in all cases, now I have this problem.

Starting compilation...
Compiling CCScript
Finished compiling CCScript
Compiling Project C:/Users/User/Desktop/EB PT-PT Translation/Projeto
Compiling Used Ranges...
Finished compiling Used Ranges in 0.00s
Compiling Patches...
Finished compiling Patches in 0.00s
Compiling Character Substitutions...
Finished compiling Character Substitutions in 0.00s
Compiling CCScript Labels...
Finished compiling CCScript Labels in 0.03s
Compiling Skip Names...
Finished compiling Skip Names in 0.00s
Compiling Miscellaneous Text...
ERROR: TableEntryInvalidYmlRepresentationError: String cannot be written in 3 bytes or less: Para a fila

Do I need to type a bigger string?

**Comment by ShadowOne333** [comment]
The contrary, the string is too big.
Check this message:

> ERROR: TableEntryInvalidYmlRepresentationError: String cannot be written in 3 bytes or less: Para a fila

That means that you are limited to 3 bytes or less, or in other words, 3 letters (I believe).
What text are you trying to translate?

**Comment by Rocadinis** [comment]
This happened on the Row Back and on the Row Front values (the values were too big, apparently). I changed both, and I got that error on the Row To value, so I shortened both of the front and back values and wrote more on the Row To value.

Note: I didn't punctuate these ones in order to solve the previous problem.

  Row Back:  de Tras
  Row Front:  da Frente
  Row To: 'Para a fila'

**Comment by ShadowOne333** [comment]
Yep, as I thought, you are limited to only 3 letters there.
Each byte = each letter.

Check how I handled it in my Spanish translation here:
https://github.com/ShadowOne333/EarthBound-Spanish-Translation/blob/master/text_misc.yml

I simply wrote "A", because I couldn't write "A esta fila" or something similar.
I think this line refers to the attack to a single enemy, so take as a translation of "To".
In my case it could be translated as "Para/Hacia/A"
"A" making a reference to "hacia" or to whom the attack will be directed to.

Try shortening it to 3 letters or less, then try compiling.

Also, take the rest of the lines in that file as reference too, you might notice some [C3] and others there, those are the punctuated/accentuated characters, that's how you need to write them in YML files.

**Comment by Rocadinis** [comment]
That seemed to work! I haven't compiled the full project yet (it's not fully done), but I'm understanding well what to do by seeing your yml file. Anyway, thank you! I don't have much time recently to continue the translation, but if I need any more help, I'll post here again. Again, thank you!

**Comment by ShadowOne333** [comment]
Great! Glad you got it working :)
Also, sorry for the late reply, I actually was just going through the issues for shits and giggles, and found yours which I thought I could lend a help with. 

If you still feel motivated enough to continue with your translation, you can always take a peek at the Spanish translation repo for reference, or also try going into the CoilSnake Tutorial section specific for translations, found here:
https://github.com/mrtenda/CoilSnake/wiki/Tutorial%3A-Translating-EarthBound

Best of luck!
