### ISSUE TITLE
EathBound rom decompile issue

### ISSUE THREAD

**Issue by HsiaLin** [mrtenda/CoilSnake#164]
When decompiling EarthBound U or USA roms i get the following:

Decompiling Doors...
- Ignoring a door at 0xf28fc that contained invalid data: Door had invalid climbability setting of 0x511
- Ignoring a door at 0xf2ab8 with an invalid type of 0x9
- Ignoring a door at 0xf2bf5 with an invalid type of 0x9
- Ignoring a door at 0xf2c01 that contained invalid data: Door had invalid climbability setting of 0x1400
- Ignoring a door at 0xf2d77 that contained invalid data: Pointer had invalid address 0xf0363
- Ignoring a door at 0xf328b with an invalid type of 0x16
- Ignoring a door at 0xf33ea with an invalid type of 0x8
- Ignoring a door at 0xf364b with an invalid type of 0x16
- Ignoring a door at 0xf3cb7 with an invalid type of 0xd
- Ignoring a door at 0xf3dba with an invalid type of 0xa
- Ignoring a door at 0xf3de5 that contained invalid data: Pointer had invalid address 0x6d0000
- Ignoring a door at 0xf40cf with an invalid type of 0x14
- Ignoring a door at 0xf41c8 with an invalid type of 0xd
- Ignoring a door at 0xf44b4 that contained invalid data: Pointer had invalid address 0x379
- Ignoring a door at 0xf484d that contained invalid data: Door had invalid climbability setting of 0x211
- Ignoring a door at 0xf485e that contained invalid data: Pointer had invalid address 0xc9
- Ignoring a door at 0xf4c0a that contained invalid data: Pointer had invalid address 0xe0403
- Ignoring a door at 0xf5186 that contained invalid data: Pointer had invalid address 0x7900c9
- Ignoring a door at 0xf53a8 that contained invalid data: Pointer had invalid address 0x9d0278
Finished decompiling Doors in 0.30s
Decompiling Sprite Groups...
Finished decompiling Sprite Groups in 5.81s

I have yet to find an EarthBound rom that decompiles ok.

**Comment by mrtenda** [comment]
If I remember correctly, this is expected. Oddly enough, the EarthBound rom has a bunch of invalid doors in it that shouldn't be there, but somehow it doesn't cause any problems during gameplay.
