### ISSUE TITLE
Help!

### ISSUE THREAD

**Issue by jojamm** [mrtenda/CoilSnake#174]
Which ccscript data file has the text for picking up Ness' cracked bat?

**Comment by ShadowOne333** [comment]
There is no specific text for the Cracked bat.
The way EarthBound manages it's item pickups, is that it uses a control code to call the correct item from a gift box in the overworld.
So basically, all items found in item boxes share the same message, all that changes is just the item ID that the item box has inside, then the control code takes said item ID and prints the correct name of the item with the control code.

**Comment by jojamm** [comment]
Got it. Thanks!
