### ISSUE TITLE
CCScript folder is empty when I decompile the ROM

### ISSUE THREAD

**Issue by Rocadinis** [mrtenda/CoilSnake#175]
When I try to decompile a plain ROM, the CCScript folder is empty, save for a "Summary.txt" file with no content on it. How can I solve this?

**Comment by ShadowOne333** [comment]
Once you open CoilSnake, there's a tab called "Decompile script".
Once you decompile a ROM, you go to that tab and browse for a clean ROM, and then where it says "Project" you browse to the same folder where you decompiled the ROM previously. It should look for a Project.snake file I believe.

**Comment by Rocadinis** [comment]
It worked! Thank you.
