### ISSUE TITLE
How to translate "The year is 199X"?

### ISSUE THREAD

**Issue by Timur13240** [mrtenda/CoilSnake#176]
Where in the project and what I should change to translate it:
![image](https://user-images.githubusercontent.com/46261539/52070655-83a86f80-25ab-11e9-8474-c4841c4e2a1c.png)
???

**Comment by ShadowOne333** [comment]
If you are using a recently created CoilSnake project, it should be in data_55.ccs:

> "[ 02 0C ][ 01 32 ]The year is 199X[ 09 ][ 00 ]"
