### ISSUE TITLE
Problem with "Item menu".

### ISSUE THREAD

**Issue by Timur13240** [mrtenda/CoilSnake#177]
If I translate this menu into "**text_misc.yml**", the problem arises that the "**Help**" tab does not work.
Maybe there is a .ccs file that will help me with this? Something like "**asm_naming_screen_characters.ccs**" or "**asm_naming_screen.ccs**"?
![image](https://user-images.githubusercontent.com/46261539/52200608-6fa68b80-2893-11e9-91c1-1a8bdff1be5c.png)

**Comment by D-Programming-Man** [comment]
Could it be that the text for the "Help" is too large to display it? You could try to expand the window to see if it's still there. It should be window 4 in the window_configuration_table.yml file. Increase the size of the window on the X axis by 1 and hopefully you should be able your "Help" text.

**Comment by Timur13240** [comment]
> Could it be that the text for the "Help" is too large to display it? You could try to expand the window to see if it's still there. It should be window 4 in the window_configuration_table.yml file. Increase the size of the window on the X axis by 1 and hopefully you should be able your "Help" text.
> 
> I do remember some instances of where if the text is too large, it'll be printed on the next line of the window, but if the window is too small to display it, then it never gets written to the window.

I added a +1 on the X axis window,  but nothing new happened, maybe this is not the window which I need?

**Comment by D-Programming-Man** [comment]
Oh, whoops. Sorry, I didn't know that the windows were first indexed as 0. So the window number you would actually need to increase the X size is window 3 and not window 4. My bad.

**Comment by Timur13240** [comment]
Ok, I'll check it out.

**Comment by Timur13240** [comment]
> Oh, whoops. Sorry, I didn't know that the windows were first indexed as 0. So the window number you would actually need to increase the X size is window 3 and not window 4. My bad.

![image](https://user-images.githubusercontent.com/46261539/52331305-04d78a80-2a22-11e9-9ce5-14cd3e7c6a71.png)
It's work!!1!
Thanks you!
