### ISSUE TITLE
How to quickly find the desired text in .css files?

### ISSUE THREAD

**Issue by Timur13240** [mrtenda/CoilSnake#178]
It would be convenient to quickly find the necessary lines in .ccs files, but there is a problem, there are many of these files, and I don’t want to search all 61 .ccs files.

**Comment by mrtenda** [comment]
On Linux or Mac OS, you could use grep from the command line to easily search all the files at once. On Windows, I have heard of people using the AstroGrep program for this.

**Comment by Timur13240** [comment]
> On Linux or Mac OS, you could use grep from the command line to easily search all the files at once. On Windows, I have heard of people using the AstroGrep program for this.

Hmm ... ok, thanks! I'll try it now!

**Comment by Timur13240** [comment]
It's work! Thank you! I finally can translate what I could not find!
