### ISSUE TITLE
Palette error

### ISSUE THREAD

**Issue by jojamm** [mrtenda/CoilSnake#179]
I have changed ness' Sprite, and I realized the colors did not match up with ness' palette, so I changed it. I have checked multiple times, and they all match up with the palette, and I still get an error! The Sprite doesn't use all of the colors in ness' Sprite, if that helps.

**Comment by Rickisthe1** [comment]
May I see the sprite change you made?

**Comment by Eagler135** [comment]
im having the same problem, but i realized that the sprite colors palette numbers are the solution but i was supposed to ask the colors in decimal numbers since that's the way i have it.

**Comment by jojamm** [comment]
@Rickisthe1 here you go.

**Comment by Rickisthe1** [comment]
Ah, I found the issue, some colors are off from the expected palette. The red color (I assume you sampled from Ness's hat) is supposed to be 335, 100, 47. The color in your sprite is 335, 100, 50. This also seems to be the case for other colors in the sprite as well.

**Comment by jojamm** [comment]
So I should just copy the colors from Ness and use them on the new Sprite?

**Comment by Rickisthe1** [comment]
Yes. Here, I fixed it. You could use this as a base. 
![001](https://user-images.githubusercontent.com/33672357/53193837-9e349e00-35d7-11e9-9690-7bcf4241c36c.png)

**Comment by vince94** [comment]
If you're using graphicsgale, I think it'd be easiest to grab an unmodified Ness file and paste your edit in, iirc it should paste using the original palette to approximate.
I remember working on a battle sprite, trying to paste something in from Photoshop or somewhere else, and it conforming to the wrong palette because I forgot to change it.
(enemy sprites don't have these kinds of limitations as long as they're 16 colors)

**Comment by Rickisthe1** [comment]
^What he said.

**Comment by jojamm** [comment]
Thanks everyone! I appreciate your help.

**Comment by Rickisthe1** [comment]
No problamo.

**Comment by Eagler135** [comment]
In any case, I was wondering... if I want to change Ness colors? How do I modify the text palette numbers of the colors to make Coilsnake accept the new colors for the "New Ness"?
