### ISSUE TITLE
Cutscenes?

### ISSUE THREAD

**Issue by jojamm** [mrtenda/CoilSnake#182]
Hello! I was wondering where I could find the files that contain the scripts for the cutscenes.

**Comment by ShadowOne333** [comment]
The cutscenes in EarthBound are nothing more of control/movement codes used to make certain sprites move in certain ways.
There is no specific file for this, as all you'll see are bytes coupled together to create a movement or control code.

You can check control codes here:
https://datacrystal.romhacking.net/wiki/EarthBound:Control_Codes

As for movement codes, I have never used them myself, but I know there are a couple files somewhere online which explain some of them, but not all, as there are hundred of them.
