### ISSUE TITLE
I can't find 'the'...

### ISSUE THREAD

**Issue by Timur13240** [mrtenda/CoilSnake#184]
When a player encounters an enemy, he is shown the message: "You engage the (enemy)". So, in my language there is no "**the**", it just should not be there, and I cannot find it to remove it. (screenshot included)
![image](https://user-images.githubusercontent.com/46261539/56513641-e7ac5580-6554-11e9-93b8-436011babd84.png)

**Comment by PhoenixBound** [comment]
The word "the" is inserted using the {user} and {target} commands in `data_58.l_0xef794b`. These commands look at an enemy's "'The' flag" to tell whether to insert the word "the" or not in an enemy's name.

If words like "the" should never be displayed, you can fix this issue by setting the `"The" flag` in `enemy_configuration_table.yml` to "false" for all enemies.

If that's too tedious, or if you need to display a different word instead, you'll need to add some assembly code.

**Comment by Timur13240** [comment]
Thank you very much!
