### ISSUE TITLE
Naming Screen Characters bug

### ISSUE THREAD

**Issue by MAGNAT2645** [mrtenda/CoilSnake#185]
Character Tables:

```
ROM[0xEFA465] = "[71 2F 72 2F 73 2F 74 2F 75 2F 76 2F 77 2F 78 2F 79 18 05 16 00 2F 5D 2F 53 18 05 00 01 2F 7A 2F 7B 2F 7C 2F 7D 2F 7E 2F 7F 2F 80 2F 81 2F 82 18 05 16 01 2F 57 2F AE 18 05 00 02 2F 83 2F \
84 2F 85 2F 86 2F 87 2F 88 2F 89 2F 8A 2F B0 18 05 16 02 2F 5E 2F 5F 18 05 00 03 2F B1 2F B2 2F B3 2F B4 2F B5 2F B6 2F 50 18 05 16 03 2F 51 2F AC 18 05 00 04 2F 60 2F 61 2F 62 2F 63 2F 64 2F 65 2F 66 2F 67 2F 68 2F 69 18 05 16 04 2F 6F 2F AF 02 \
18 05 00 00 2F 91 2F 92 2F 93 2F 94 2F 95 2F 96 2F 97 2F 98 2F 99 18 05 16 00 2F 5D 2F 53 18 05 00 01 2F 9A 2F 9B 2F 9C 2F 9D 2F 9E 2F 9F 2F A0 2F A1 2F A2 18 05 16 01 2F 57 2F AE 18 05 00 02 2F A3 2F A4 \
2F A5 2F A6 2F A7 2F A8 2F A9 2F AA 2F C0 18 05 16 02 2F 5E 2F 5F 18 05 00 03 2F C1 2F C2 2F C3 2F C4 2F C5 2F C6 2F 50 18 05 16 03 2F 51 2F AC 18 05 00 04 2f 60 2F 61 2F 62 2F 63 2F 64 2F 65 2F 66 2F 67 2F 68 2F 69]"

ROM[0xEFA56B] = "[71 2F 72 2F 73 2F 74 2F 75 2F 76 2F 77 2F 78 2F 79 18 05 16 00 2F 5D 2F 53 18 05 00 01 2F 7A 2F 7B 2F 7C 2F 7D 2F 7E 2F 7F 2F 80 2F 81 2F 82 18 05 16 01 2F 57 2F AE 18 05 00 02 2F 83 2F \
84 2F 85 2F 86 2F 87 2F 88 2F 89 2F 8A 2F B0 18 05 16 02 2F 5E 2F 5F 18 05 00 03 2F B1 2F B2 2F B3 2F B4 2F B5 2F B6 2F 50 18 05 16 03 2F 51 2F AC 18 05 00 04 2F 60 2F 61 2F 62 2F 63 2F 64 2F 65 2F 66 2F 67 2F 68 2F 69 18 05 16 04 2F 6F 2F AF 02 \
18 05 00 00 2F 91 2F 92 2F 93 2F 94 2F 95 2F 96 2F 97 2F 98 2F 99 18 05 16 00 2F 5D 2F 53 18 05 00 01 2F 9A 2F 9B 2F 9C 2F 9D 2F 9E 2F 9F 2F A0 2F A1 2F A2 18 05 16 01 2F 57 2F AE 18 05 00 02 2F A3 2F A4 \
2F A5 2F A6 2F A7 2F A8 2F A9 2F AA 2F C0 18 05 16 02 2F 5E 2F 5F 18 05 00 03 2F C1 2F C2 2F C3 2F C4 2F C5 2F C6 2F 50 18 05 16 03 2F 51 2F AC 18 05 00 04 2f 60 2F 61 2F 62 2F 63 2F 64 2F 65 2F 66 2F 67 2F 68 2F 69]"
```

Naming screen mist text:
```
import asm65816

naming_screen_one:
//	"[18 05 00 05][2F]ПЕЧАТНЫЕ[18 05 07 05][2F]прописные[18 05 00 06][2F]Не важно[18 05 11 06][2F]Назад[18 05 19 06][2F]ОК[02]"
	"[18 05 00 05][2F][81][76][89][71][84][7F][B2][76][18 05 07 05][2F][A1][A2][A0][A1][9A][A3][9F][C2][96][18 05 00 06][2F][7F][96] [93][91][98][9F][A0][18 05 11 06][2F][7F][91][99][91][95][18 05 19 06][2F][80][7C][02]"

naming_screen_two:
//	"[18 05 00 05][2F]ПЕЧАТНЫЕ[18 05 07 05][2F]прописные[18 05 11 06][2F]Назад[18 05 19 06][2F]ОК[02]"
	"[18 05 00 05][2F][81][76][89][71][84][7F][B2][76][18 05 07 05][2F][A1][A2][A0][A1][9A][A3][9F][C2][96][18 05 11 06][2F][7F][91][99][91][95][18 05 19 06][2F][80][7C][02]"

ROM[0xEFA66C] = goto(naming_screen_one)
ROM[0xEFA6A7] = goto(naming_screen_two)
```

I've problem that every character after `...B5 2F B6 2F...` (character table) seems to be broken somehow. (**B6** is the last **Я** before **!**)
Also there's invisible space item (`...B6 2F 50...`) before **!**
So, every character after `...2F 50...` shows different symbol if you select them.

For example, **T** instead of **!** (all numbers are this big **O** instead of...numbers)
![EarthBoundRUS004](https://user-images.githubusercontent.com/11666918/56978595-4d21c700-6b91-11e9-83b9-9b2da33d1f0d.png)

And naming player isn't same as naming characters
![EarthBoundRUS005](https://user-images.githubusercontent.com/11666918/56978609-5448d500-6b91-11e9-8c24-9547ee275164.png)

And this happens when note item selected (seems to behave like "Don't Care")
![EarthBoundRUS006](https://user-images.githubusercontent.com/11666918/56978660-73476700-6b91-11e9-961d-982da287b33d.png)

Font:
![0](https://user-images.githubusercontent.com/11666918/56978685-7fcbbf80-6b91-11e9-93c4-9bfb72647933.png)

**Comment by ShadowOne333** [comment]
I think the main problem here is that you might have moved stuff around too much both vertically and horizontally to the point where there is some text overflow, in like the text goes beyond the edge of the window, overwriting other lines.

With that said, user PhoenixBound was kind enough to rework the previous scripts, and narrowed them all down into one simple script, with an easier to read code and also easier to reposition each row/column.

Take a look:
https://gist.github.com/ShadowOne333/6bc2e1c88697a4f3265cc8572ebafee7

Try with that new script, and then be sure to avoid having letters overlapping each other.

**Comment by MAGNAT2645** [comment]
Does this script require EB++? I had some strange bugs with EB++, so I refused to use it. Maybe I just have outdated asm65816 and I don't know where to get a newer one.

**Comment by ShadowOne333** [comment]
Nope, it doesn't require EB++ at all.
Not even asm65816.ccs even, so you can just pop this script in place of the other two you used before, and start tweaking it according to your needs.

**Comment by MAGNAT2645** [comment]
So i can't actually use numbers after all alphabet due to overflow?

**Comment by ShadowOne333** [comment]
That I am not sure of.
You could try for sure.
Make room for whatever new row you want to add, and make sure to add it in place of the numbers row (text_pos(X,3) ).
Then, move the "CAPITAL" and "small" rows (and anything with text_pos(0,4)/text_pos(7,4) ) to text_pos(0,5) and text_pos(7,5), and then move the numbers table to text_pos(0,4) in its place.

It could work, I just never tried it.

**Comment by MAGNAT2645** [comment]
Nah, it's not helped.
![изображение](https://user-images.githubusercontent.com/11666918/57320657-d0569600-7118-11e9-8ca5-6511d0374b3d.png)

! acts like T, note is 0, all numbers is something like O, ? is 3, something like O is 4;
CAPITAL and small acts like that circle or O too.;
Don't care works fine, Backspace don't work at all, OK works fine.

**Comment by ShadowOne333** [comment]
Try removing the numbers row entirely, and see if everything else behaves accordingly.
Don't forget to move the "CAPITAL" row to where the numbers were in text_pos(0,4)

**Comment by MAGNAT2645** [comment]
```
footer_main: {		// offset EFA66C
	/*
	text_pos(0, 5) "[2F]ЗАГЛАВНЫЕ" text_pos(8, 5) "[2F]строчные"
	text_pos(0, 6) "[2F]Не важно" text_pos(20, 6) "[2F]Назад" text_pos(25, 6) "[2F]ОК"
	*/
	text_pos(0, 5) "[2F][79][71][74][7D][71][73][7F][B2][76]" text_pos(8, 5) "[2F][A3][A4][A2][A0][A9][9F][C2][96]"
	text_pos(0, 6) "[2F][7F][96] [93][91][98][9F][A0]" text_pos(20, 6) "[2F][7F][91][99][91][95]" text_pos(25, 6) "[2F][80][7C]"
	eob
}

footer_player: {	// offset EFA6A7
	/*
	text_pos(0, 5) "[2F]ЗАГЛАВНЫЕ" text_pos(8, 5) "[2F]строчные"
	text_pos(20, 6) "[2F]Назад" text_pos(25, 6) "[2F]ОК"
	*/
	text_pos(0, 5) "[2F][79][71][74][7D][71][73][7F][B2][76]" text_pos(8, 5) "[2F][A3][A4][A2][A0][A9][9F][C2][96]"
	text_pos(20, 6) "[2F][7F][91][99][91][95]" text_pos(25, 6) "[2F][80][7C]"
	eob
}
```

**Comment by ShadowOne333** [comment]
Oh I mean the main_capital and player_capital, they should have the same data between each other.
Same for the _small ones.

**Comment by MAGNAT2645** [comment]
Yeah, they're same (i mean position and etc., not alphabet set).

**Comment by MAGNAT2645** [comment]
Hmm, same problem.
![изображение](https://user-images.githubusercontent.com/11666918/57322753-bc616300-711d-11e9-8a69-71a384ba0a97.png)

```
main_capital: {		// offset EFA460
	/*
	text_pos(0, 0) "[2F]А[2F]Б[2F]В[2F]Г[2F]Д[2F]Е[2F]Ё[2F]Ж[2F]З"		text_pos(22, 0) "[2F]-[2F]#"
	text_pos(0, 1) "[2F]И[2F]Й[2F]К[2F]Л[2F]М[2F]Н[2F]О[2F]П[2F]Р"	text_pos(22, 1) "[2F]'[2F]~"
	text_pos(0, 2) "[2F]С[2F]Т[2F]У[2F]Ф[2F]Х[2F]Ц[2F]Ч[2F]Ш[2F]Щ"	text_pos(22, 2) "[2F].[2F][5F]"
	text_pos(0, 3) "[2F]Ъ[2F]Ы[2F]Ь[2F]Э[2F]Ю[2F]Я[2F] "				text_pos(22, 3) "[2F]![2F][AC]"
	text_pos(0, 4) "[2F]0[2F]1[2F]2[2F]3[2F]4[2F]5[2F]6[2F]7[2F]8[2F]9"	text_pos(22, 4) "[2F]?[2F][AF]"
	*/
	text_pos(0, 0) "[2F][71][2F][72][2F][73][2F][74][2F][75][2F][76][2F][77][2F][78][2F][79]"		text_pos(22, 0) "[2F]-[2F]#"
	text_pos(0, 1) "[2F][7A][2F][7B][2F][7C][2F][7D][2F][7E][2F][7F][2F][80][2F][81][2F][82]"	text_pos(22, 1) "[2F]'[2F]~"
	text_pos(0, 2) "[2F][83][2F][84][2F][85][2F][86][2F][87][2F][88][2F][89][2F][8A][2F][B0]"	text_pos(22, 2) "[2F].[2F][5F]"
	text_pos(0, 3) "[2F][B1][2F][B2][2F][B3][2F][B4][2F][B5][2F][B6][2F] "						text_pos(22, 3) "[2F]![2F][AC]"
	//text_pos(0, 4) "[2F]0[2F]1[2F]2[2F]3[2F]4[2F]5[2F]6[2F]7[2F]8[2F]9"						text_pos(22, 4) "[2F]?[2F][AF]"
																							text_pos(22, 4) "[2F]?[2F][AF]"
	eob
}

main_small: {		// offset EFA4E3
	/*
	text_pos(0, 0) "[2F]а[2F]б[2F]в[2F]г[2F]д[2F]е[2F]ё[2F]ж[2F]з"		text_pos(22, 0) "[2F]-[2F]#"
	text_pos(0, 1) "[2F]и[2F]й[2F]к[2F]л[2F]м[2F]н[2F]о[2F]п[2F]р"		text_pos(22, 1) "[2F]'[2F]~"
	text_pos(0, 2) "[2F]с[2F]т[2F]у[2F]ф[2F]х[2F]ц[2F]ч[2F]ш[2F]щ"		text_pos(22, 2) "[2F].[2F][5F]"
	text_pos(0, 3) "[2F]ъ[2F]ы[2F]ь[2F]э[2F]ю[2F]я[2F] "					text_pos(22, 3) "[2F]![2F][AC]"
	text_pos(0, 4) "[2F]0[2F]1[2F]2[2F]3[2F]4[2F]5[2F]6[2F]7[2F]8[2F]9"	text_pos(22, 4) "[2F]?[2F][AF]"
	*/
	text_pos(0, 0) "[2F][91][2F][92][2F][93][2F][94][2F][95][2F][96][2F][97][2F][98][2F][99]"		text_pos(22, 0) "[2F]-[2F]#"
	text_pos(0, 1) "[2F][9A][2F][9B][2F][9C][2F][9D][2F][9E][2F][9F][2F][A0][2F][A1][2F][A2]"	text_pos(22, 1) "[2F]'[2F]~"
	text_pos(0, 2) "[2F][A3][2F][A4][2F][A5][2F][A6][2F][A7][2F][A8][2F][A9][2F][AA][2F][C0]"	text_pos(22, 2) "[2F].[2F][5F]"
	text_pos(0, 3) "[2F][C1][2F][C2][2F][C3][2F][C4][2F][C5][2F][C6][2F] "						text_pos(22, 3) "[2F]![2F][AC]"
	//text_pos(0, 4) "[2F]0[2F]1[2F]2[2F]3[2F]4[2F]5[2F]6[2F]7[2F]8[2F]9"						text_pos(22, 4) "[2F]?[2F][AF]"
																							text_pos(22, 4) "[2F]?[2F][AF]"
	eob
}

player_capital: {	// offset EFA566
	/*
	text_pos(0, 0) "[2F]А[2F]Б[2F]В[2F]Г[2F]Д[2F]Е[2F]Ё[2F]Ж[2F]З"		text_pos(22, 0) "[2F]-[2F]#"
	text_pos(0, 1) "[2F]И[2F]Й[2F]К[2F]Л[2F]М[2F]Н[2F]О[2F]П[2F]Р"	text_pos(22, 1) "[2F]'[2F]~"
	text_pos(0, 2) "[2F]С[2F]Т[2F]У[2F]Ф[2F]Х[2F]Ц[2F]Ч[2F]Ш[2F]Щ"	text_pos(22, 2) "[2F].[2F][5F]"
	text_pos(0, 3) "[2F]Ъ[2F]Ы[2F]Ь[2F]Э[2F]Ю[2F]Я[2F] "				text_pos(22, 3) "[2F]![2F][AC]"
	text_pos(0, 4) "[2F]0[2F]1[2F]2[2F]3[2F]4[2F]5[2F]6[2F]7[2F]8[2F]9"	text_pos(22, 4) "[2F]?[2F][AF]"
	*/
	text_pos(0, 0) "[2F][71][2F][72][2F][73][2F][74][2F][75][2F][76][2F][77][2F][78][2F][79]"		text_pos(22, 0) "[2F]-[2F]#"
	text_pos(0, 1) "[2F][7A][2F][7B][2F][7C][2F][7D][2F][7E][2F][7F][2F][80][2F][81][2F][82]"	text_pos(22, 1) "[2F]'[2F]~"
	text_pos(0, 2) "[2F][83][2F][84][2F][85][2F][86][2F][87][2F][88][2F][89][2F][8A][2F][B0]"	text_pos(22, 2) "[2F].[2F][5F]"
	text_pos(0, 3) "[2F][B1][2F][B2][2F][B3][2F][B4][2F][B5][2F][B6][2F] "						text_pos(22, 3) "[2F]![2F][AC]"
	//text_pos(0, 4) "[2F]0[2F]1[2F]2[2F]3[2F]4[2F]5[2F]6[2F]7[2F]8[2F]9"						text_pos(22, 4) "[2F]?[2F][AF]"
																							text_pos(22, 4) "[2F]?[2F][AF]"
	eob
}

player_small: {		// offset EFA5E9
	/*
	text_pos(0, 0) "[2F]а[2F]б[2F]в[2F]г[2F]д[2F]е[2F]ё[2F]ж[2F]з"		text_pos(22, 0) "[2F]-[2F]#"
	text_pos(0, 1) "[2F]и[2F]й[2F]к[2F]л[2F]м[2F]н[2F]о[2F]п[2F]р"		text_pos(22, 1) "[2F]'[2F]~"
	text_pos(0, 2) "[2F]с[2F]т[2F]у[2F]ф[2F]х[2F]ц[2F]ч[2F]ш[2F]щ"		text_pos(22, 2) "[2F].[2F][5F]"
	text_pos(0, 3) "[2F]ъ[2F]ы[2F]ь[2F]э[2F]ю[2F]я[2F] "					text_pos(22, 3) "[2F]![2F][AC]"
	text_pos(0, 4) "[2F]0[2F]1[2F]2[2F]3[2F]4[2F]5[2F]6[2F]7[2F]8[2F]9"	text_pos(22, 4) "[2F]?[2F][AF]"
	*/
	text_pos(0, 0) "[2F][91][2F][92][2F][93][2F][94][2F][95][2F][96][2F][97][2F][98][2F][99]"		text_pos(22, 0) "[2F]-[2F]#"
	text_pos(0, 1) "[2F][9A][2F][9B][2F][9C][2F][9D][2F][9E][2F][9F][2F][A0][2F][A1][2F][A2]"	text_pos(22, 1) "[2F]'[2F]~"
	text_pos(0, 2) "[2F][A3][2F][A4][2F][A5][2F][A6][2F][A7][2F][A8][2F][A9][2F][AA][2F][C0]"	text_pos(22, 2) "[2F].[2F][5F]"
	text_pos(0, 3) "[2F][C1][2F][C2][2F][C3][2F][C4][2F][C5][2F][C6][2F] "						text_pos(22, 3) "[2F]![2F][AC]"
	//text_pos(0, 4) "[2F]0[2F]1[2F]2[2F]3[2F]4[2F]5[2F]6[2F]7[2F]8[2F]9"						text_pos(22, 4) "[2F]?[2F][AF]"
																							text_pos(22, 4) "[2F]?[2F][AF]"
	eob
}
```

**Comment by ShadowOne333** [comment]
Just tried out by just replacing the numbers row for custom characters, and it works fine for me.
Be sure to grab the clean .ccs file yet again, and only modify the numbers row, which should be this one for small:
`	text_pos(0, 3) "[2F][C1][2F][C2][2F][C3][2F][C4][2F][C5][2F][C6][2F] "						text_pos(22, 3) "[2F]![2F][AC]"
	//text_pos(0, 4) "[2F]0[2F]1[2F]2[2F]3[2F]4[2F]5[2F]6[2F]7[2F]8[2F]9"	`

And this one for capital:
`	text_pos(0, 3) "[2F][B1][2F][B2][2F][B3][2F][B4][2F][B5][2F][B6][2F] "						text_pos(22, 3) "[2F]![2F][AC]"
	//text_pos(0, 4) "[2F]0[2F]1[2F]2[2F]3[2F]4[2F]5[2F]6[2F]7[2F]8[2F]9"	`

By changing only those two, you should get the proper characters.
Also, please note that in my test, I filled ALL the spaces up from 0 up to 9 with other characters.
So try to continue the layout from B0 up to B9 in the number row, and the same thing for C0 up to C9.

**Comment by ShadowOne333** [comment]
I managed to get the Naming Screen working with a 5th row for characters and also the CAPITAL row working properly with some help by PhoenixBound and some peeking at a disassembly of EB.

Check the updated gist:
https://gist.github.com/ShadowOne333/6bc2e1c88697a4f3265cc8572ebafee7

Be sure to replace the values with your font ones, and test it in-game.
Let me know if it works.

**Comment by MAGNAT2645** [comment]
Somehow i've fixed naming screen character recognition but there's still problem that "small" item just prints O instead of character set toggle.

Also i just shifted Backspace button and it stopped working.

```
ROM[0xC20912] = {	// Table for the naming screen character recognition.
// Each value is an offset value added to the starting control code [18 05 XX YY] or text_pos(x,y). 
// For example, the first value [05] corresponds to the letter 'A', since [18 05 XX YY] takes up bytes 0-3, [2F] being byte 4 and the actual 'A' letter being the 0x05 byte. Then there's another 2F byte, which is 0x06 or byte 6, and then the next letter 'B', which is the 0x07 byte, and so on.
// The table has been split into the corresponding rows, with only the 5th row being modified to include additional characters.
// FF means there's a blank space.
"[05 07 09 0B 0D 0F 11 13 15 FF FF 1B 1D FF \
  23 25 27 29 2B 2D 2F 31 33 FF FF 39 3B FF \
  41 43 45 47 49 4B 4D 4F 51 FF FF 57 59 FF \
  5F 61 63 65 67 69 6B FF FF FF FF 71 73 FF \
  79 7B 7D 7F 81 83 85 87 89 8B FF 91 90 FF \
  FF FF FF FF FF FF FF FF FF 8F 1F 80 FF 03 FF 03 01 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00]" 
}
```
```
footer_main: {		// offset EFA66C
	/*
	text_pos(0, 5) "[2F]ЗАГЛАВНЫЕ" text_pos(8, 5) "[2F]строчные"
	text_pos(0, 6) "[2F]Не важно" text_pos(20, 6) "[2F]Назад" text_pos(25, 6) "[2F]ОК"
	*/
	text_pos(0, 5) "[2F][79][71][74][7D][71][73][7F][B2][76]" text_pos(8, 5) "[2F][A3][A4][A2][A0][A9][9F][C2][96]"
	text_pos(0, 6) "[2F][7F][96] [93][91][98][9F][A0]" text_pos(20, 6) "[2F][7F][91][99][91][95]" text_pos(25, 6) "[2F][80][7C]"
	eob
}

footer_player: {	// offset EFA6A7
	/*
	text_pos(0, 5) "[2F]ЗАГЛАВНЫЕ" text_pos(8, 5) "[2F]строчные"
	text_pos(20, 6) "[2F]Назад" text_pos(25, 6) "[2F]ОК"
	*/
	text_pos(0, 5) "[2F][79][71][74][7D][71][73][7F][B2][76]" text_pos(8, 5) "[2F][A3][A4][A2][A0][A9][9F][C2][96]"
	text_pos(20, 6) "[2F][7F][91][99][91][95]" text_pos(25, 6) "[2F][80][7C]"
	eob
}
```

**Comment by ShadowOne333** [comment]
Do you have this portion of code?
`ROM[0xC1E992] = CMP_i (0x0005)	// Originally CMP_i (0x0004). Changed to 0x0005 so that CAPITAL and small are printed in the 5th row instead of the 4th one. Change the value to match the X position/row of the CAPITAL/small row so it's detected in the game properly`

**Comment by MAGNAT2645** [comment]
Yeah, i have 0xC1E992 code. Is there any way to do same but for Backspace X position?

**Comment by ShadowOne333** [comment]
For BackSpace X position:
`ROM[0xC1E934] = CMP_i (0x0011)`

For Okay X position:
`ROM[0xC1E939] = CMP_i (0x0019)`

Change the 11 and 19 accordingly.

**Comment by MAGNAT2645** [comment]
Now it works. Thanks a lot! Backspace have (20,6) position so i put 0x0014 and it worked.

**Comment by MAGNAT2645** [comment]
Also i have question about Run button patch. There's a bug with sprites when you're trying to teleport but fail. Is there any way to fix that?

**Comment by ShadowOne333** [comment]
Don't use the Run patch from CoilSnake, that one has that known bug.
Disable it, and instead add this .ccs to your ccscript folder:
https://github.com/ShadowOne333/MaternalBound/blob/master/ccscript/asm_run.ccs

**Comment by MAGNAT2645** [comment]
I tried it but sprites still doesn't appear when you fail teleport.

**Comment by ShadowOne333** [comment]
Check your patches.yml, and make sure that the Run button ones are disabled there.
I know my CCS/ASM hack works, because that is exactly the reason why I did an entirely new Run button patch from scratch, due to that bug.
I just went ahead and checked in a hack compiled yesterday with my CCS, and the teleport sprites work fine on my end.

**Comment by MAGNAT2645** [comment]
Weird, I checked recently and bug was, and right now it is not appears.
Maybe i really forgot to disable it via patches.yml

**Comment by ShadowOne333** [comment]
Oh at least it doesn't happen anymore.
Good thing it's working now!
