### ISSUE TITLE
Can't find a Project.snake file anywhere

### ISSUE THREAD

**Issue by endercraft4** [mrtenda/CoilSnake#187]
Hi, I was able to decompile the earthbound rom alright, but I can't decompile the script or use the "EB Project Editor 2.0" since it can't find the Project.snake file. I also looked in a file browser and can't find project.snake. I am using Coilsnake 3.33 on Galium OS (Linux. Based on Ubuntu 16.04). I compiled and installed coilsnake from source.

**Comment by LittlestCube** [comment]
3.33 is actually not recommended, as it has been known to be buggy. Try 3.0 (commit c056be3521f0a50cd6c3b8ae20f0a89016b7f1aa)

**Comment by ShadowOne333** [comment]
Could you please try again with the most recent commit?
It should make a Project.snake file just fine.
Please let us know if it worked to properly close this issue.
