### ISSUE TITLE
OutofBoundsError during Decompile

### ISSUE THREAD

**Issue by SeniorSnore** [mrtenda/CoilSnake#188]
I am using WIndows 10 and using 
![image](https://user-images.githubusercontent.com/15458981/59545594-64710580-8eee-11e9-8ff5-3e68e160cc6e.png)

I am getting the following error when I decompile the ROM
![image](https://user-images.githubusercontent.com/15458981/59545601-7c488980-8eee-11e9-8559-d95b602032f3.png)
 
Any ideas on how to resolve this issue?

**Comment by mrtenda** [comment]
what is the size in bytes of the rom file you are decompiling?

**Comment by SeniorSnore** [comment]
The .sfc file is 1712 KB.

**Comment by mrtenda** [comment]
The EB rom should be around 3 megabytes in size. Your rom file is incorrect, so CoilSnake can't decompile it.

**Comment by SeniorSnore** [comment]
Thank you, I will look for a new ROM
