### ISSUE TITLE
Something wrong

### ISSUE THREAD

**Issue by MAGNAT2645** [mrtenda/CoilSnake#207]
There's some problems with CoilSnake 4.
After compilation with CoilSnake 4.0 (previous versions works fine), game looks like corrupted.
![изображение](https://user-images.githubusercontent.com/11666918/64902909-a49c7b80-d6c9-11e9-964a-059d686803ee.png)

And this happens with every image, logo etc.
![изображение](https://user-images.githubusercontent.com/11666918/64902915-be3dc300-d6c9-11e9-865d-568c7c0e68ec.png)

Only sound seems to be fine.

Also, as i understood, now you have to manually copy ebpp.ccs and ebpp_std.ccs to your project.
Can ebpp.ccs conflict with EBPP_Disassembly_HardwareCompatible_v1_1.ccs or they have different functions?

EDIT: Yes, i have upgraded project via CoilSnake. Made backup but i want to use CoilSnake 4.

**Comment by MAGNAT2645** [comment]
I did some changes to new Cast module (earlier used TileMolester for this) and now it doesn't work.
![изображение](https://user-images.githubusercontent.com/11666918/64903081-43c27280-d6cc-11e9-8855-293eeca92348.png)

**Comment by mrtenda** [comment]
Yes, you understand correctly about manually copying `ebpp.ccs` and `ebpp_std.ccs`. These files only contain ccscript functions to help you use EB++ and do not contain any ASM modifications. `EBPP_Disassembly_HardwareCompatible_v1_1.ccs` is the file that contains the ASM modifications.

Some questions:
- Are you compiling with a clean base ROM?
- What size is your base ROM?
- What happens if you remove `EBPP_Disassembly_HardwareCompatible_v1_1.ccs` from your project and instead enable EB++ through the `patches.yml` file?

**Comment by MAGNAT2645** [comment]
1) I use [Earthbound (U) [!].smc](https://www.fantasyanime.com/legacy/earthb_down.htm)
2) Expanded base ROM to 4 MB
3) Black screen. Game doesn't load at all.

**Comment by MAGNAT2645** [comment]
Oh, after 2nd compilation, game is working.

**Comment by MAGNAT2645** [comment]
I think, i can close this now.

**Comment by MAGNAT2645** [comment]
I'll reopen this issue because game looks broken when you're talking to someone who have dynamic name title (like title_ness, title_paula, title_dog). Dialogues with title() works fine.

And this happens since i enabled EB++ 0.999 (and removed EB++ 1.1).

**Comment by MAGNAT2645** [comment]
So, after some additional testing, i think that ebpp_std is kinda broken with EB++ 0.999 (from patches.yml).
Here's example with title_dog:
![BrokenTitle](https://user-images.githubusercontent.com/11666918/65173954-5a205380-da69-11e9-9eca-1268f578ec76.gif)

**Comment by MAGNAT2645** [comment]
That's weird, after starting new game game doesn't freeze like at gif above.

**Comment by mrtenda** [comment]
Oh, yeah, that makes sense. I think the different versions of EB++ use SRAM and memory in gemeral differently, so savefiles and savestates might not be compatible across them.

Does the EB++ disassembly ccs work with a new savefile? I asked h.s on IRC, and he said `title_ness` works fine for him with CoilSnake 4 and the EB++ ccscript version (though he may be using a different version of the EB++ disassembly ccs).

**Comment by MAGNAT2645** [comment]
Did you mean ebpp.ccs and ebpp_std.ccs? I took them from mobile-sprout.
Now it works fine if you just start new game.
I hope that there will be no new bugs so i'll close this issue for now.

**Comment by mrtenda** [comment]
I meant `EBPP_Disassembly_HardwareCompatible_v1_1.ccs`. I wonder if the problem with `EBPP_Disassembly_HardwareCompatible_v1_1.ccs` would be resolved if you used a fresh savefile.

(Of course, you can just keep using the patches.yml version of EB++, that works too)

**Comment by MAGNAT2645** [comment]
I think that 1.1 doesn't work properly with CoilSnake 4 because there's something weird as you can see at screenshots from first post. This happens even on game startup (without using any savestates, by pressing Run button from CoilSnake).

**Comment by MAGNAT2645** [comment]
Also, game doesn't freeze now with savestates (savestates with old SRAM from EB++ 1.1).
There's just some glitches but you can get out of dialogue.
![BrokenTitleButNotFreeze](https://user-images.githubusercontent.com/11666918/65350449-34c54e00-dbff-11e9-8ed3-07c54a2688d6.gif)
![BrokenTitleButNotFreeze2](https://user-images.githubusercontent.com/11666918/65350537-64745600-dbff-11e9-9d69-ac10048c7974.gif)

**Comment by MAGNAT2645** [comment]
So yeah, i've compiled project to new savefile and EB++ disassembly works fine.
Is there any way to "clear out" existing RAM/generic memory, so your next compilations won't do this glitches and crashes?

**Comment by MAGNAT2645** [comment]
Removed oops and srm files and recompiled to previous savefile. It seems to work fine (again).
