### ISSUE TITLE
Incorrect Color Palette

### ISSUE THREAD

**Issue by BadBoyBeeps** [mrtenda/CoilSnake#211]
Hey, guys! I want to edit the sprites in the Earthbound ROM I have, however, when I finished and I go to "Compile" it tells me a message saying that I used an incorrect color pallette. I've tried everything. I can send you the modifications I made if that is nescassary. I just need some help

**Comment by Rickisthe1** [comment]
Did you use any colors other than the ones already in the palette?

**Comment by BadBoyBeeps** [comment]
No. I don't know how to change the palettes so that my skin works

**Comment by Rickisthe1** [comment]
Could you post your sprite?

**Comment by Rickisthe1** [comment]
(Not sure if you've already read the tutorial or not, but the CoilSnake tutorial has a sprite section.)

**Comment by BadBoyBeeps** [comment]
![001](https://user-images.githubusercontent.com/55516164/65197155-fa697e80-da4f-11e9-8832-6b5533f288e5.png)



![002](https://user-images.githubusercontent.com/55516164/65197161-00f7f600-da50-11e9-8cd2-8c896246ad90.png)

**Comment by Rickisthe1** [comment]
Looking at your Ness change, you changed the 3rd color in the palette to a white color. You changed the RGB to be 255, 255, 255 when it should be 200, 200, 200.

**Comment by Rickisthe1** [comment]
Also, not sure if you know this, but the green color is transparent.

**Comment by BadBoyBeeps** [comment]
Oh okay. Do you know where I can find the Ness file on sprite_colorpallettes.yml and where to place these changes?

**Comment by Rickisthe1** [comment]
You don't really need to do that unless you want to change the palette color. What you could do is copy your current sprite and paste them into a vanilla sprite. It'll keep the original palette. You can do this by using GraphicsGale's section tool. (Ctrl + C and Ctrl + V)

**Comment by BadBoyBeeps** [comment]
So, let me get this straight, I need to paste the current sprite in a vanilla sprite, which is the original sprite for Ness

**Comment by Rickisthe1** [comment]
If you do want to change the palettes, keep in mind it affects any sprite that uses it, not just the ones you want.
And yes, that's one of the simple methods.

**Comment by BadBoyBeeps** [comment]
I don't have the original Ness sprite. I hate to be a bugger, but can you show me how to do it. Haven't done this before

**Comment by Rickisthe1** [comment]
Oh, no problem! Let me just record something real quick.

**Comment by BadBoyBeeps** [comment]
alright

**Comment by BadBoyBeeps** [comment]
almost finished

**Comment by Rickisthe1** [comment]
https://youtu.be/2BWR9-sYAZU The commands I used were Ctrl + A, Ctrl + C, and Ctrl + V in order.

**Comment by BadBoyBeeps** [comment]
could I paste it into the same file as the modified sprite?

**Comment by BadBoyBeeps** [comment]
never mind I got it! Thanks a lot!!

**Comment by Rickisthe1** [comment]
Np
