### ISSUE TITLE
Status window behaves oddly

### ISSUE THREAD

**Issue by Lyrositor** [mrtenda/CoilSnake#54]
I first noticed this while working on CCScriptWriter: the Status window, once you get more than one party member, has a tendency to behave oddly (particularly with Paula, although I seem to recall problems with Jeff too). I have tried this with a clean CoilSnake project, and I still find the problem (the problem is however very inconsistent).

To sum up, sometimes bringing up the Status window (usually when looking at Paula's stats) makes the game crash (with weird colors, enlarged pixels, etc.), or it gives odd results when exiting the status window, as seen below:

![Reference_00000](https://f.cloud.github.com/assets/1495312/72149/a5617f30-6005-11e2-96db-08e326e5d2e3.png)

**Comment by john-soklaski** [comment]
I'm interested in checking this out, but haven't been able to reproduce. @mrtenda  do you know if this was fixed?

**Comment by mrtenda** [comment]
This was so long ago, and I haven't ever heard of anyone reproducing it, so I suggest we just close it.
